import { Button } from "std-widgets.slint";

export component MainWindow inherits Window {
    preferred-width: 300px;
    preferred-height: 350px;
    min-width: 200px;
    min-height: 250px;
    title: "Niko :3";
    default-font-size: 14px;
    icon: @image-url("assets/images/niko.png"); 

    property <image> current-image: @image-url("assets/images/niko.png");

    VerticalLayout {
        spacing: 10px;
        padding: 10px;
        alignment: center;

        Image {
            source: root.current-image;
            image-fit: contain;
            image-rendering: pixelated;
        }
        
        HorizontalLayout {
            alignment: center;
            
            Button {
                text: ":3";
                width: 50px;
                height: 50px;
                clicked => { root.play_meow(); }
            }
        }
    }

    callback play_meow();
}
